### ISSUE TITLE
0.2.1 version numbering inconsistency. pypi - github

### ISSUE THREAD

**Issue by lars-kolbowski** [mobiusklein/pyteomics.cythonize#2]
Hi, 
in https://github.com/mobiusklein/pyteomics.cythonize/commit/0c48bdb1bb74b92e0fc29d7e1ba5ae41c40cfe26 you bumped the version to 0.2.1 but [pypi](https://pypi.org/project/pyteomics.cythonize/#history) shows a 0.2.1 already released on Jun 26, 2018. 
Not trying to be annoying :smile: just wondering if this could lead to problems when releasing the new version to pypi.

**Comment by mobiusklein** [comment]
I've bumped the version number and re-released the code unchanged as v0.2.2. https://pypi.org/project/pyteomics.cythonize/
